# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:  
  solution: './APITempoDio/*.sln'
  buildPlataform: 'Any CPU'
  buildConfiguration: 'Release'
  
steps:

- task: UseDotNet@2
  displayName: 'Install .Net SDK' 
  inputs: 
    packageType: 'sdk'  
    version: '8.x'

- script: dotnet restore $(solution)
  displayName: 'Restore Solution' 

- script: dotnet build $(solution) --configuration $(buildConfiguration)
  displayName: 'Build Solution'   
  
- script: dotnet test $(solution) --configuration $(buildConfiguration)  --no-build --collect:"Xplat Code Coverage"
  displayName: 'Teste Solution' 
  
- task: Docker@2
  inputs:
    containerRegistry: 'acrapidemolfog'
    repository: 'api-dio-test'
    command: 'buildAndPush'
    Dockerfile: './APITempoDio/APITempoDio/Dockerfile' 


